apiVersion: v1
kind: ReplicationController
metadata:
  name: my-todolist
spec:
  replicas: 2
  selector:
    app: my-todolist
  template:
    metadata:
      labels:
        app: my-todolist
    spec:                     
      containers: 
      - name: todolist
        image: my-todolist
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
